### ISSUE TITLE
Logging connection time

### ISSUE THREAD

**Issue by ElGigi** [atlasphp/Atlas.Pdo#1]
Hi,

I think it will be interesting to save the connection to the database, with a connection time.
This can be good information for debugging an unusually slow application, due to the slow PDO connection, for example.

The statement for logging can be: "CONNECTION"

Regards.

**Comment by pmjones** [comment]
Hey @ElGigi --

The connection time is currently saved as "start" in the log entry (it's the unix microtime when the query started). Cf. <http://atlasphp.io/cassini/pdo/connection.html#1-6-1-6>. Is that what you meant?

**Comment by ElGigi** [comment]
Thanks for your response, it's not exactly what i mean.

"start" is the start of query, but not of the PDO connection.
When PDO establish connection the server, it can take time. And this time can be long in some case, like busy server.

What i mean, it's the duration of PDO object creation. For distants servers, it's can do time.

**Comment by pmjones** [comment]
Oh, now that's interesting. Let me see what I can do.

**Comment by pmjones** [comment]
The only way to track it would be by tracking the creation of the PDO instance itself, using the $queryLogger. The constructor does not create the PDO instance, so that's no good. Connection::new() *does* create the instance, but it does not have the $queryLogger, so it can't be tracked there either.

In all, I don't think this can be done under the current setup. Closing the issue; I can reopen if you have a working suggestion, and thanks for your patience.
